First version of CLI
sodascience/metasynth pull request #142
Opened 2023-08-09 08:31 UTC by vankesteren

Added a command line interface, with the following help file:

```
usage: metasynth [-h] [-n NUM_ROWS] [-p] [-v] input output

Synthesize data from Generative Metadata Format .json file.

positional arguments:
  input                 Input file.
  output                Output file. File extension should be one of: .csv, .feather, .parquet, .pkl, .xlsx

options:
  -h, --help            show this help message and exit
  -n NUM_ROWS, --num_rows NUM_ROWS
                        Number of rows to synthesize
  -p, --print_only      print one-row data frame to console and exit
  -v, --version         show program's version number and exit
```

This will pave the way for stable, versioned docker containers which directly use this CLI, e.g., 
```docker
docker sodascience/metasynth:v0.4 metatdatafile.json outputfile.csv
```
Those containers could be automatically built whenever we release on GitHub as part of our CI

2023-08-10 09:43 UTC, vankesteren commented
Ok the tests now finally pass!!

2023-08-10 21:40 UTC, qubixes requested changes
That's a nice feature indeed! I just have some small comments, looks very neat!

2023-08-10 21:40 UTC, qubixes commented on metasynth/__main__.py
> +        help="print six-row data frame to console and exit",
```suggestion
        help="preview six-row synthesized data frame to console and exit",
```

Maybe changing it to `--preview` makes sense?

2023-08-10 21:40 UTC, qubixes commented on tests/test_cli.py
Nice test!

2023-08-10 21:40 UTC, qubixes commented on metasynth/__main__.py
> +            pkl_file.close()
```suggestion
```
The nice thing about context managers is that they close automatically!

2023-08-10 21:40 UTC, qubixes commented on metasynth/__main__.py
> +            f"Output file format ({args.output.suffix}) incorrect." +
```suggestion
            f"Unsupported output file format ({args.output.suffix})." +
```

2023-08-10 21:40 UTC, qubixes commented on metasynth/__main__.py
> +    sys.exit(0)
Is there a reason to have this?

2023-08-10 21:40 UTC, qubixes commented on metasynth/__main__.py
> +        sys.exit(0)
Probably nicer to just return from the function?

2023-08-10 21:40 UTC, qubixes commented on metasynth/__main__.py
I think it's a great idea to have a CLI interface. I do think we should have sub commands though. It is likely we would want to be able to create GMF files as well from the command line. `metasynth synthesize` and `metasynth create-metadata` perhaps?

2023-08-11 09:16 UTC, vankesteren commented on metasynth/__main__.py
Good point, I have two thoughts on it:

1. Creating metadata is an interactive thing. You need to load the data with the correct types, add a `spec`, and check whether everything runs correctly. Are we sure we want to allow people to do this with a simple CLI?
2. This will be some work, let's leave that for a next PR.

2023-08-11 09:19 UTC, vankesteren commented on tests/test_cli.py
yeah, took some time to figure out but it works now!

2023-08-11 09:22 UTC, qubixes commented on metasynth/__main__.py
> Good point, I have two thoughts on it:
> 
>     1. Creating metadata is an interactive thing. You need to load the data with the correct types, add a `spec`, and check whether everything runs correctly. Are we sure we want to allow people to do this with a simple CLI?
> 
>     2. This will be some work, let's leave that for a next PR.

I could see the `spec` being loaded in with a JSON file or something (That might be useful anyway with bigger datasets). Another sub command could be creating a visualization for example? I think in most cases we do want people to use it interactively, but regarding 2.): I'm not suggesting to make the `create-metadata` sub command  part of this PR, but if we want to support it in the future, it would be good to prepare for it with having sub commands (even if it's only one for now). Then we won't have to break the API in the future!

2023-08-11 09:56 UTC, vankesteren commented on metasynth/__main__.py
I've now added a "shim" subcommand, to keep the code simple.

usage is now 
```sh
metasynth synthesize input.json output.csv
```

2023-08-11 12:24 UTC, merged